### PR TITLE
Closes: #351 - Update link-checker.yml

### PR DESCRIPTION
**Pull request by ShrirangB**
ci: do not open new issues on duplicated Link Checker Report #351

Closes: #XXX
> *Be noted that XXX is the issue ID*

## What is the purpose of the change

> Add a description of the overall background and high level changes that this PR introduces

*(E.g.: This pull request improves documentation of area A by adding ....)*

### CODE REVIEW

**Comment by tungbq** [comment]
Hi @ShrirangB thanks for your contribution on this repository, do you have a chance to test/verify this change?

**Comment by ShrirangB** [comment]
ok, I will try to test it but if require any guidance can I ping you here?

**Comment by tungbq** [comment]
> ok, I will try to test it but if require any guidance can I ping you here?

Sure @ShrirangB feel free to ping here if you need any help. Thanks

**Comment by ShrirangB** [comment]
I am not able to figure out how to test it can you please guide me through the steps?

**Comment by tungbq** [comment]
> I am not able to figure out how to test it can you please guide me through the steps?
Hello @ShrirangB you can trigger your own workflow with your branch in the Github Action tab on Github, for example:
image

**Pull request closed without merging**
